### ISSUE TITLE
Wildcard domains

### ISSUE THREAD

**Issue by pimjansen** [AxaFrance/oidc-client#1157]
### Issue and Steps to Reproduce

Maybe its even a stupid question but i could not find anything suited in the documentation on this (yet). I use the serviceworker to link it with my keycloak instance which overal (besides SSL stuff) works fine locally.

In production im having different tenants each on their own domain. The code however is not aware of all these tenants. Is there a way to handle this situation? For instance define a wildcard in the domain specification?

Thanks!

### Versions
latest

**Comment by guillaume-chervet** [comment]
Hi @pimjansen , i think i have erased by inadvertance a part of the documentation.
Thank you for your issue.

Domain can accept regex like : https://github.com/AxaFrance/oidc-client/blob/8f24b119613fef5d7214826528bdb04c931a1986/packages/oidc-client-service-worker/src/utils/domains.ts#L16

So you can do it. If i remenber well you can set * and it will work.
It is not very secure because hacker coulb be able to send access tokens to his own website.

**Comment by guillaume-chervet** [comment]
The best option is to dynamically generate TrustedDomain file.

**Comment by guillaume-chervet** [comment]
Like it it won't :)

**Comment by pimjansen** [comment]
Ok it does not seem to work though. This is my config now:

```js
const trustedDomains = {
    default: {
        oidcDomains: [
            "https://auth.domain.nl",
            "https:\/\/(\w+)\.(\w+)\.domain\.nl(:[0-9]+)?",
        ],
        accessTokenDomains: [
            'https://tenant.dev.api.domain.nl',
            "https:\/\/(\w+)\.(\w+)\.api\.domain\.nl(:[0-9]+)?",
        ]
    },
};
```

Any idea/tips? The accessTokenDomains do not seem to work since there is no token injected when i remove the non regex line there. See https://regex101.com/r/ZTw81M/1

**Comment by guillaume-chervet** [comment]
Domains is bad naming from my part.

It check in fact the full Path :  "https:\/\/(\w+)\.(\w+)\.api\.domain\.nl(:[0-9]+)*?"
You may tests with a stars at the end of your regex then it soould work.

**Comment by pimjansen** [comment]
That does work though however its not a real valid regex?
